PRODUCT_COPY_FILES += \
	vendor/lenovo/jd2018/lib/libril-qc-hal-qmi.so:system/lib/jd2018/libril-qc-hal-qmi.so \
	vendor/lenovo/jd2018/lib/libril-qc-ltedirectdisc.so:system/lib/jd2018/libril-qc-ltedirectdisc.so \
	vendor/lenovo/jd2018/lib/libril-qc-qmi-1.so:system/lib/jd2018/libril-qc-qmi-1.so \
	vendor/lenovo/jd2018/lib/libril-qc-radioconfig.so:system/lib/jd2018/libril-qc-radioconfig.so \
	vendor/lenovo/jd2018/lib/libril-qcril-hook-oem.so:system/lib/jd2018/libril-qcril-hook-oem.so \
	vendor/lenovo/jd2018/lib/libril.so:system/lib/jd2018/libril.so \
	vendor/lenovo/jd2018/lib/librilqmiservices.so:system/lib/jd2018/librilqmiservices.so \
	vendor/lenovo/jd2018/lib/libqti-gt-prop.so:system/lib/jd2018/libqti-gt-prop.so \
	vendor/lenovo/jd2018/lib/libqti-iopd-client.so:system/lib/jd2018/libqti-iopd-client.so \
	vendor/lenovo/jd2018/lib/libqti-perfd-client.so:system/lib/jd2018/libqti-perfd-client.so \
	vendor/lenovo/jd2018/lib/libqti-perfd.so:system/lib/jd2018/libqti-perfd.so \
	vendor/lenovo/jd2018/lib/libqti-util.so:system/lib/jd2018/libqti-util.so \
	vendor/lenovo/jd2018/lib/libqti-utils.so:system/lib/jd2018/libqti-utils.so \
	vendor/lenovo/jd2018/lib/libqtigef.so:system/lib/jd2018/libqtigef.so \
	vendor/lenovo/jd2018/lib/hw/activity_recognition.sdm660.so:system/lib/jd2018/hw/activity_recognition.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/audio.primary.sdm660.so:system/lib/jd2018/hw/audio.primary.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/bootctrl.sdm660.so:system/lib/jd2018/hw/bootctrl.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/camera.sdm660.so:system/lib/jd2018/hw/camera.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/gatekeeper.sdm660.so:system/lib/jd2018/hw/gatekeeper.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/gralloc.sdm660.so:system/lib/jd2018/hw/gralloc.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/hwcomposer.sdm660.so:system/lib/jd2018/hw/hwcomposer.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/keystore.sdm660.so:system/lib/jd2018/hw/keystore.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/lights.sdm660.so:system/lib/jd2018/hw/lights.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/memtrack.sdm660.so:system/lib/jd2018/hw/memtrack.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/sound_trigger.primary.sdm660.so:system/lib/jd2018/hw/sound_trigger.primary.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/thermal.sdm660.so:system/lib/jd2018/hw/thermal.sdm660.so \
	vendor/lenovo/jd2018/lib/hw/vulkan.sdm660.so:system/lib/jd2018/hw/vulkan.sdm660.so \
	vendor/lenovo/jd2018/lib64/libril-qc-hal-qmi.so:system/lib64/jd2018/libril-qc-hal-qmi.so \
	vendor/lenovo/jd2018/lib64/libril-qc-ltedirectdisc.so:system/lib64/jd2018/libril-qc-ltedirectdisc.so \
	vendor/lenovo/jd2018/lib64/libril-qc-qmi-1.so:system/lib64/jd2018/libril-qc-qmi-1.so \
	vendor/lenovo/jd2018/lib64/libril-qc-radioconfig.so:system/lib64/jd2018/libril-qc-radioconfig.so \
	vendor/lenovo/jd2018/lib64/libril-qcril-hook-oem.so:system/lib64/jd2018/libril-qcril-hook-oem.so \
	vendor/lenovo/jd2018/lib64/libril.so:system/lib64/jd2018/libril.so \
	vendor/lenovo/jd2018/lib64/librilqmiservices.so:system/lib64/jd2018/librilqmiservices.so \
	vendor/lenovo/jd2018/lib64/libqti-gt-prop.so:system/lib64/jd2018/libqti-gt-prop.so \
	vendor/lenovo/jd2018/lib64/libqti-iopd-client.so:system/lib64/jd2018/libqti-iopd-client.so \
	vendor/lenovo/jd2018/lib64/libqti-perfd-client.so:system/lib64/jd2018/libqti-perfd-client.so \
	vendor/lenovo/jd2018/lib64/libqti-perfd.so:system/lib64/jd2018/libqti-perfd.so \
	vendor/lenovo/jd2018/lib64/libqti-util.so:system/lib64/jd2018/libqti-util.so \
	vendor/lenovo/jd2018/lib64/libqti-utils.so:system/lib64/jd2018/libqti-utils.so \
	vendor/lenovo/jd2018/lib64/libqtigef.so:system/lib64/jd2018/libqtigef.so \
	vendor/lenovo/jd2018/lib64/hw/activity_recognition.sdm660.so:system/lib64/jd2018/hw/activity_recognition.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/audio.primary.sdm660.so:system/lib64/jd2018/hw/audio.primary.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/bootctrl.sdm660.so:system/lib64/jd2018/hw/bootctrl.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/gatekeeper.sdm660.so:system/lib64/jd2018/hw/gatekeeper.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/gralloc.sdm660.so:system/lib64/jd2018/hw/gralloc.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/hwcomposer.sdm660.so:system/lib64/jd2018/hw/hwcomposer.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/keystore.sdm660.so:system/lib64/jd2018/hw/keystore.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/lights.sdm660.so:system/lib64/jd2018/hw/lights.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/memtrack.sdm660.so:system/lib64/jd2018/hw/memtrack.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/sound_trigger.primary.sdm660.so:system/lib64/jd2018/hw/sound_trigger.primary.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/thermal.sdm660.so:system/lib64/jd2018/hw/thermal.sdm660.so \
	vendor/lenovo/jd2018/lib64/hw/vulkan.sdm660.so:system/lib64/jd2018/hw/vulkan.sdm660.so

PRODUCT_PROPERTY_OVERRIDES := \
	ro.product.board=sdm660 \
	ro.board.patform=sdm660 \
	ro.config.vc_call_vol_steps=6 \
	ro.com.google.clientidbase=android-lenovo \
	ro.com.google.clientidbase.ms=android-lenovo \
	ro.com.google.clientidbase.am=android-lenovo \
	ro.com.google.clientidbase.gmm=android-lenovo \
	ro.com.google.clientidbase.yt=android-lenovo \
	persist.vendor.radio.add_power_save=1 \
	qemu.hw.mainkeys=0 \
	video.disable.ubwc=1 \
	dalvik.vm.heapgrowthlimit=256m \
	dalvik.vm.heapstartsize=8m \
	dalvik.vm.heapsize=512m \
	dalvik.vm.heaptargetutilization=0.75 \
	dalvik.vm.heapminfree=512k \
	dalvik.vm.heapmaxfree=8m \
	ro.hardware.nfc_nci=nqx.default \
	persist.radio.multisim.config=dsds \
	persist.vendor.qcomsysd.enabled=1 \
	keyguard.no_require_sim=true \
	ro.carrier=unknown \
	ro.vendor.extension_library=libqti-perfd-client.so \
	persist.vendor.radio.apm_sim_not_pwdn=1 \
	persist.vendor.radio.sib16_support=1 \
	persist.vendor.radio.custom_ecc=1 \
	persist.vendor.radio.rat_on=combine \
	persist.radio.schd.cache=3500 \
	ro.build.shutdown_timeout=0 \
	ro.frp.pst=/dev/block/bootdevice/by-name/frp \
	qcom.bluetooth.soc=cherokee \
	af.fast_track_multiplier=1 \
	vendor.audio_hal.period_size=192 \
	persist.vendor.audio.fluence.voicecall=true \
	persist.vendor.audio.fluence.voicerec=true \
	ro.vendor.audio.sdk.fluencetype=fluence \
	persist.vendor.audio.fluence.speaker=false \
	vendor.audio.tunnel.encode=false \
	persist.vendor.audio.ras.enabled=false \
	vendor.audio.offload.buffer.size.kb=64 \
	audio.offload.min.duration.secs=30 \
	audio.offload.video=true \
	vendor.audio.offload.track.enable=true \
	audio.deep_buffer.media=true \
	vendor.audio.offload.multiaac.enable=true \
	vendor.audio.dolby.ds2.enabled=false \
	vendor.audio.dolby.ds2.hardbypass=false \
	vendor.audio.offload.multiple.enabled=false \
	vendor.audio.offload.passthrough=false \
	ro.vendor.audio.sdk.ssr=false \
	vendor.audio.offload.gapless.enabled=true \
	vendor.audio.safx.pbe.enabled=true \
	vendor.audio.parser.ip.buffer.size=262144 \
	vendor.audio.flac.sw.decoder.24bit=true \
	persist.vendor.bt.a2dp_offload_cap=sbc-aac \
	vendor.audio.use.sw.alac.decoder=true \
	vendor.audio.use.sw.ape.decoder=true \
	vendor.audio.hw.aac.encoder=true \
	vendor.fm.a2dp.conc.disabled=true \
	vendor.audio.noisy.broadcast.delay=600 \
	persist.vendor.audio.hifi.int_codec=true \
	vendor.audio.offload.pstimeout.secs=3 \
	ro.vendor.sensors.facing=false \
	ro.vendor.sdk.sensors.gestures=false \
	rild.libpath=/system/lib64/jd2018/libril-qc-qmi-1.so \
	persist.vendor.qti.telephony.vt_cam_interface=1 \
	ro.vendor.sensors.cmc=true \
	ro.product.first_api_level=27 \
	persist.camera.HAL3.enabled=1
